server:
  port: 8888
spring:
  application:
    name: ugo - a online shopping platform
  datasource:
    url: jdbc:mysql:///ugo?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  # mapper-locations 默认位置为 classpath:mapper/*.xml
  # mapper-locations:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.boot.ugo.entity

# SpringSecurity请求白名单
request:
  white: /ugo/cus/hello,/ugo/cus/login,/ugo/test/*,/ugo/goo/*,/ugo/cat/*
